-- SQLite
ALTER TABLE LOCATIONS RENAME TO LOCATIONS_OLD;

CREATE TABLE LOCATIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    TOTAL FLOAT(10,2) NOT NULL,
    CUSTOMER_ID INTEGER,
    CAR_ID INTEGER,
    EMPLOYEE_ID INTEGER,
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
    FOREIGN KEY (CAR_ID) REFERENCES CARS(ID)
);

INSERT INTO LOCATIONS SELECT * FROM LOCATIONS_OLD;

DROP TABLE LOCATIONS_OLD;

SELECT * FROM LOCATIONS;

SELECT EMPLOYEES.NAME 
FROM LOCATIONS
JOIN EMPLOYEES ON EMPLOYEES.ID = LOCATIONS.EMPLOYEE_ID
GROUP BY EMPLOYEES.NAME
HAVING COUNT(LOCATIONS.EMPLOYEE_ID) >= 2;