-- SQLite
ALTER TABLE EMPLOYEES RENAME TO EMPLOYEES_OLD;

CREATE TABLE EMPLOYEES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(16) NOT NULL,
    CONTRACT_DATE DATETIME NOT NULL,
    POSITION_ID INTEGER,
    FOREIGN KEY(POSITION_ID) REFERENCES POSITIONS(ID)
);

INSERT INTO EMPLOYEES SELECT * FROM EMPLOYEES_OLD;

DROP TABLE EMPLOYEES_OLD;

SELECT * FROM EMPLOYEES;

SELECT EMPLOYEES.NAME, POSITIONS.DESCRIPTION
FROM EMPLOYEES
JOIN POSITIONS ON EMPLOYEES.POSITION_ID = POSITIONS.ID;