-- SQLite
SELECT LOCATIONS.ID AS 'Id da locação',
CUSTOMERS.NAME AS 'Nome do cliente',
CARS.NAME AS 'Nome do automóvel',
EMPLOYEES.NAME AS 'Nome do funcionário'
FROM LOCATIONS
JOIN CUSTOMERS ON LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID
JOIN CARS ON LOCATIONS.CAR_ID = CARS.ID
JOIN EMPLOYEES ON LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID;